### PR TITLE
Convert to rebar3 usage

### PR DESCRIPTION
**Pull request by dgud**
Hi Tony

I've rewritten cl to use rebar3 instead of the old rebar usage, they have removed the 'C' support
cludge so I have brought back the old Makefile in c_src.

So can you take a quick look/test?
If you think it 's ok I'll push a package to hex.pm.

Compiles and runs tests (and edoc and dialyzer) rebar3 do compile, ct

A preparation for a hex package

### CODE REVIEW

**Comment by tonyrog** [comment]
Question. Is it possible to run the old rebar on this code?
I am not ready to switch over to rebar3 since I am using the "cludge" of compiling C code in plenty of projects ( I am partly responsible for the cross compile support in rebar :-)

**Comment by dgud** [comment]
The cludge is not that bad when dealing with non windows OS's, but our (my) rebar.config.script
is the only way to solve Win32 and that is a cludge.

The makefile is a bit cludgy as well, in a need of configure script.

Also sometime we need to move on I guess..

That is solvable in two ways:
You switch to rebar3 and use a plugin in your other projects, that makes it work as before (I have not tested that).  :-)

If you insist of being old and work again changes :-D
We might be able to make cl work with both rebar and rebar3, there was something written for that somewhere, I can take a look at that if you want.

**Comment by tonyrog** [comment]
I am pro-change :-)
But there are so many projects to change so I am consider to be even more old and grumpy and switch back to Makefiles again. I normally mix C and Erlang code and prefer to use one build system for everything.

**Comment by dgud** [comment]
Yeah, I kind of agree about the Makefiles, but it seems that we/OTP are changing to rebar3, so
I thought I should play with it, and 'cl' was a good project to play with.

And publishing a hex package is a good idea anyway.

I will try to make it work with rebar again.

**Comment by dgud** [comment]
Can you test this one, for me it works with both rebar and rebar3.
It uses the Makefile in both cases, tested on linux and win32.

**Comment by tonyrog** [comment]
Works for me on mac. Merged. Thanks

**Pull request merged**
